steps:
  - id: Build
    name: "node:22"
    script: |
      #!/usr/bin/env bash
      npm install --global pnpm@11.9.0
      pnpm install
      pnpm run build
      pnpm --filter emitter run emit
    secretEnv:
      [
        "TWITTER_API_KEY",
        "TWITTER_API_SECRET",
        "TWITTER_ACCESS_TOKEN_SECRET",
        "TWITTER_ACCESS_TOKEN",
      ]
  - name: us-docker.pkg.dev/firebase-cli/us/firebase
    args: ["deploy", "--project=$PROJECT_ID", "--only=hosting:main"]
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/TWITTER_API_KEY/versions/latest
      env: "TWITTER_API_KEY"
    - versionName: projects/$PROJECT_ID/secrets/TWITTER_API_SECRET/versions/latest
      env: "TWITTER_API_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/TWITTER_ACCESS_TOKEN/versions/latest
      env: "TWITTER_ACCESS_TOKEN"
    - versionName: projects/$PROJECT_ID/secrets/TWITTER_ACCESS_TOKEN_SECRET/versions/latest
      env: "TWITTER_ACCESS_TOKEN_SECRET"
