packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
injectWorkspacePackages: true
