import type { Metadata } from "next";
import { useLocale } from "next-intl";
import { IBM_Plex_Mono, IBM_Plex_Sans, Newsreader } from "next/font/google";
import localFont from 'next/font/local';

const redaction10 = localFont({
  src: [
    {
      path: '../assets/fonts/redaction/Redaction_10-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/redaction/Redaction_10-Italic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../assets/fonts/redaction/Redaction_10-Bold.woff2',
      weight: '700',
      style: 'normal',
    }
  ],
  variable: '--font-redaction-10',
});

const redaction35 = localFont({
  src: [
    {
      path: '../assets/fonts/redaction/Redaction_35-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/redaction/Redaction_35-Italic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../assets/fonts/redaction/Redaction_35-Bold.woff2',
      weight: '700',
      style: 'normal',
    }
  ],
  variable: '--font-redaction-35'
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  weight: ["400", "700"]
});


const materialSymbolsOutlined = localFont({
  src: "../assets/fonts/material_symbols/MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].woff2",
  variable: '--font-material-symbols-outlined',
  display: 'block'
});

export const metadata: Metadata = {
  title: "Turkish Parliament Chart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = useLocale();
  return (
    <html lang={locale} className={`h-full ${redaction10.variable} ${redaction35.variable} ${ibmPlexMono.variable} ${materialSymbolsOutlined.variable}`}>
      <body
        className="antialiased p-2 h-full"
      >
        {children}
      </body>
    </html>
  );
}
